//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mailSender.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class senderList
    {
        public int id { get; set; }
        public string email { get; set; }
        public System.DateTime sendDate { get; set; }
        public string detail { get; set; }
    }
}
